FROM node:7.7.2-alpine

#caso você esteja usando mac,
#S comente a linha de cima e descomente a de baixo
#FROM arm64v8/node

WORKDIR /usr/app
COPY package.json .

RUN npm install --quiet

COPY . .

CMD ["node", "app.js"]